### ISSUE TITLE
company-mode

### ISSUE THREAD

**Issue by BrianHicks** [k1LoW/emacs-ansible#2]
If `company-mode` is enabled, https://github.com/k1LoW/emacs-ansible/blob/master/ansible.el#L140 will result in an error since `ac-user-dictionary-files` is not enabled. Would it be possible to add to company-mode's autocomplete if it's enabled?

**Comment by k1LoW** [comment]
`ansible.el` do not support `company-mode`. I merged #3 . 

thx @peterhoeg
