### ISSUE TITLE
Buffer not fontified automatically on ansible mode enter

### ISSUE THREAD

**Issue by OverkillGuy** [k1LoW/emacs-ansible#23]
When turning on `ansible` mode, the buffer doesn't automatically recolor based on the mode's fontification rules.

Workaround: Go to beginning of buffer, add a character then remove it, forcing a refontification.

I assume this traces down to a missing call to some well-known "refontify" method of Emacs, but don't have the ELisp-fu to prove it.
I would love to be pointed to the adequate method so I can create a PR.

**Comment by k1LoW** [comment]
I have no idea about refontify. 
If you are able to resolve this, I would encourage you to send a pull request. ⭐️

**Comment by OverkillGuy** [comment]
This issue seems to have been fixed in recent release. Closing.
Thanks for your work!
