### ISSUE TITLE
Skip --vault-password-file when ansible-vault-password-file is nil

### ISSUE THREAD

**Issue by kqr** [k1LoW/emacs-ansible#34]
Due to a bug in Ansible under Python 3, `ansible-vault` fails to run when given the `--vault-password-file` parameter. I find the `auto-decrypt-encrypt` functionality very convenient, but given this Ansible bug it only decrypts; it never encrypts again. This is slightly dangerous, as you can imagine.

A workaround while waiting for the Ansible bug to be fixed is to remove the `--vault-password-file` argument from the command string in `ansible.el:335`. However, this could be done more generally: if `ansible-vault-password-file` is nil, there's no reason to supply that argument at all to the command, and let Ansible try to figure it all out through the environment. 

The way I've phrased it makes it sound like it's only good for working around a highly specific Ansible bug, but the reason I propose it is because it sounds like something that might make sense generally as well.

If this is acceptable, I can submit a PR.

**Comment by kqr** [comment]
This is the corresponding Ansible bug: https://github.com/ansible/ansible/issues/63512

**Comment by soulawaker** [comment]
I agree. I also made a workaround, reflecting your tip.

**Comment by k1LoW** [comment]
@kqr sorry for the late reply. and thank you for your offer !
