### ISSUE TITLE
autoload yasnippet snippets

### ISSUE THREAD

**Issue by catesandrew** [k1LoW/emacs-ansible#4]
https://github.com/k1LoW/emacs-ansible/blob/master/ansible.el#L133-L135

``` lisp
;;;###autoload
(eval-after-load 'yasnippet
  '(ansible::snippets-initialize))
```

The following line doesn't allow finer customization, instead it always loads the ansible snippets even if the user is not in a ansible minor mode. Is it possible to remove those lines so if yasnippet-global-mode is disabled and only loaded selectively per major mode then the ansible snippets won't be autoloaded with them?

**Comment by k1LoW** [comment]
mmm...need a plan B
